"""add tsv to document chunks

Revision ID: 032ed5254a6b
Revises: 3683b2666266
Create Date: 2026-04-23 03:33:21.763972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '032ed5254a6b'
down_revision: Union[str, Sequence[str], None] = '3683b2666266'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('tsv', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_chunks', 'tsv')
    # ### end Alembic commands ###
