"""add expected document ids to golden set

Revision ID: 47b3df526ee9
Revises: f6738dc00eb9
Create Date: 2026-04-25 21:43:03.419627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47b3df526ee9'
down_revision: Union[str, Sequence[str], None] = 'f6738dc00eb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('golden_set_questions', sa.Column('expected_document_ids', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('golden_set_questions', 'expected_document_ids')
    # ### end Alembic commands ###
