"""add chunk config fields

Revision ID: 49db97577151
Revises: 7823bfdbe9e1
Create Date: 2026-04-24 18:14:24.461958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49db97577151'
down_revision: Union[str, Sequence[str], None] = '7823bfdbe9e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('chunk_size', sa.Integer(), nullable=True))
    op.add_column('document_chunks', sa.Column('chunk_overlap', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('chunk_size', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('chunk_overlap', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'chunk_overlap')
    op.drop_column('documents', 'chunk_size')
    op.drop_column('document_chunks', 'chunk_overlap')
    op.drop_column('document_chunks', 'chunk_size')
    # ### end Alembic commands ###
