"""add golden set questions

Revision ID: 57e5f117ed52
Revises: ea7d20da4cf7
Create Date: 2026-04-24 17:52:48.465610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57e5f117ed52'
down_revision: Union[str, Sequence[str], None] = 'ea7d20da4cf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('golden_set_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('expected_answer', sa.Text(), nullable=True),
    sa.Column('expected_document_id', sa.Integer(), nullable=True),
    sa.Column('expected_source_identifier', sa.String(length=255), nullable=True),
    sa.Column('difficulty', sa.String(length=50), nullable=True),
    sa.Column('tags_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('golden_set_questions')
    # ### end Alembic commands ###
