"""add retrieved chunks log

Revision ID: ea7d20da4cf7
Revises: 032ed5254a6b
Create Date: 2026-04-24 17:46:41.996742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea7d20da4cf7'
down_revision: Union[str, Sequence[str], None] = '032ed5254a6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('retrieved_chunks_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query_log_id', sa.Integer(), nullable=False),
    sa.Column('chunk_id', sa.Integer(), nullable=False),
    sa.Column('retrieval_rank', sa.Integer(), nullable=False),
    sa.Column('retrieval_score', sa.Float(), nullable=True),
    sa.Column('rerank_score', sa.Float(), nullable=True),
    sa.Column('was_used_in_prompt', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['query_log_id'], ['query_logs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retrieved_chunks_log_chunk_id'), 'retrieved_chunks_log', ['chunk_id'], unique=False)
    op.create_index(op.f('ix_retrieved_chunks_log_query_log_id'), 'retrieved_chunks_log', ['query_log_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_retrieved_chunks_log_query_log_id'), table_name='retrieved_chunks_log')
    op.drop_index(op.f('ix_retrieved_chunks_log_chunk_id'), table_name='retrieved_chunks_log')
    op.drop_table('retrieved_chunks_log')
    # ### end Alembic commands ###
